//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneMvc.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMANET
    {
        public int EMANET1 { get; set; }
        public Nullable<int> KITAP_ID { get; set; }
        public Nullable<int> UYE_ID { get; set; }
        public Nullable<System.DateTime> ALINIS_TARIHI { get; set; }
        public Nullable<System.DateTime> TESLIM_TARIHI { get; set; }
        public Nullable<bool> TESLIM_EDILDI_MI { get; set; }
    }
}
