//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneMvc.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISTEK
    {
        public int ISTEK_ID { get; set; }
        public int UYE_ID { get; set; }
        public Nullable<int> KITAP_ID { get; set; }
        public string TIP { get; set; }
        public System.DateTime TARIH { get; set; }
        public string DURUM { get; set; }
        public string ACIKLAMA { get; set; }
    }
}
