//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneMvc.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class KITAP
    {
        public int KITAP_ID { get; set; }
        public string AD { get; set; }
        public string YAZAR { get; set; }
        public string ISBN { get; set; }
        public Nullable<int> BASIM_YILI { get; set; }
        public Nullable<int> KATEGORI_ID { get; set; }
        public Nullable<int> RAF_ID { get; set; }
        public Nullable<bool> DURUM { get; set; }
    }
}
