//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneMvc.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LibraryDBEntities1 : DbContext
    {
        public LibraryDBEntities1()
            : base("name=LibraryDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EMANET> EMANET { get; set; }
        public virtual DbSet<KATEGORI> KATEGORI { get; set; }
        public virtual DbSet<KITAP> KITAP { get; set; }
        public virtual DbSet<RAF> RAF { get; set; }
        public virtual DbSet<RAF_KATEGORI> RAF_KATEGORI { get; set; }
        public virtual DbSet<RAF_TRANSFER> RAF_TRANSFER { get; set; }
        public virtual DbSet<ROLE> ROLE { get; set; }
        public virtual DbSet<View_EmanetKitap> View_EmanetKitap { get; set; }
        public virtual DbSet<KITAP_KATEGORI> KITAP_KATEGORI { get; set; }
        public virtual DbSet<UYE> UYE { get; set; }
        public virtual DbSet<REZERVASYON> REZERVASYON { get; set; }
        public virtual DbSet<VW_Rezervasyon> VW_Rezervasyon { get; set; }
        public virtual DbSet<View_RAF_KITAP> View_RAF_KITAP { get; set; }
        public virtual DbSet<ISTEK> ISTEK { get; set; }
        public virtual DbSet<View_ISTEK> View_ISTEK { get; set; }
    }
}
