//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneMvc.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RAF
    {
        public int RAF_ID { get; set; }
        public string RAF_AD { get; set; }
        public Nullable<int> KAPASITE { get; set; }
        public Nullable<byte> KAT_NO { get; set; }
    }
}
