//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneMvc.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RAF_TRANSFER
    {
        public int TRANSFER_ID { get; set; }
        public Nullable<int> KITAP_ID { get; set; }
        public Nullable<int> ESKI_RAF_ID { get; set; }
        public Nullable<int> YENI_RAF_ID { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
    }
}
