//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneMvc.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UYE
    {
        public int UYE_ID { get; set; }
        public string AD { get; set; }
        public string SOYAD { get; set; }
        public string EMAIL { get; set; }
        public string TELEFON { get; set; }
        public Nullable<System.DateTime> UYELIK_TARIHI { get; set; }
        public Nullable<int> ROLE_ID { get; set; }
        public Nullable<byte> CEZA_PUAN { get; set; }
        public string PAROLA_HASH { get; set; }
    }
}
