//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneMvc.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_RAF_KITAP
    {
        public string RAF_AD { get; set; }
        public Nullable<int> KAPASITE { get; set; }
        public Nullable<byte> KAT_NO { get; set; }
        public Nullable<int> Expr1 { get; set; }
        public string AD { get; set; }
        public string YAZAR { get; set; }
        public string ISBN { get; set; }
        public Nullable<int> BASIM_YILI { get; set; }
        public Nullable<bool> DURUM { get; set; }
        public int ID { get; set; }
        public int KATEGORI_ID { get; set; }
        public int RAF_ID { get; set; }
        public int KITAP_ID { get; set; }
        public int kategorı_id { get; set; }
        public string KATEGORI_ADI { get; set; }
    }
}
