//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneMvc.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_ISTEK
    {
        public int KITAP_ID { get; set; }
        public int ISTEK_ID { get; set; }
        public int UYEID { get; set; }
        public string UYE_AD { get; set; }
        public string UYE_SOYAD { get; set; }
        public int ID_UYE { get; set; }
        public System.DateTime TARIH { get; set; }
        public string DURUM { get; set; }
        public string TIP { get; set; }
        public Nullable<int> ID_KITAP { get; set; }
        public string ACIKLAMA { get; set; }
        public string AD { get; set; }
    }
}
