//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneMvc.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_EmanetKitap
    {
        public int KITAP_ID { get; set; }
        public string KitapAdi { get; set; }
        public string YAZAR { get; set; }
        public string ISBN { get; set; }
        public Nullable<int> KATEGORI_ID { get; set; }
        public Nullable<bool> DURUM { get; set; }
        public int EmanetID { get; set; }
        public Nullable<System.DateTime> ALINIS_TARIHI { get; set; }
        public Nullable<System.DateTime> TESLIM_TARIHI { get; set; }
        public Nullable<bool> TESLIM_EDILDI_MI { get; set; }
        public int UYE_ID { get; set; }
        public string EMAIL { get; set; }
        public string TELEFON { get; set; }
        public Nullable<System.DateTime> UYELIK_TARIHI { get; set; }
        public Nullable<int> ROLE_ID { get; set; }
        public Nullable<byte> CEZA_PUAN { get; set; }
        public string UyeAdi { get; set; }
        public string UyeSoyadi { get; set; }
    }
}
