//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneMvc.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Rezervasyon
    {
        public int UYE_ID { get; set; }
        public int REZ_ID { get; set; }
        public Nullable<System.DateTime> TALEP_TARIH { get; set; }
        public Nullable<System.DateTime> SON_GECERLILIK { get; set; }
        public Nullable<byte> DURUM { get; set; }
        public int KITAP_ID { get; set; }
        public string AD { get; set; }
        public string YAZAR { get; set; }
        public string ISBN { get; set; }
        public string UYE_AD { get; set; }
        public string SOYAD { get; set; }
        public string EMAIL { get; set; }
        public string TELEFON { get; set; }
    }
}
